# docker-compose.yaml
version: '3'
services:
    jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      restart: always
      user: root
      ports:
        - "8080:8080"
        - "50000:50000"
      container_name: "jenkins"
      volumes:
        - /home/jenkins_compose/jenkins_configuration:/var/jenkins_home
        - /var/run/docker.sock:/var/run/docker.sock
    
    webserver:
      image: nginx:latest
      container_name: webserver
      restart: always
      tty: true
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./site/www:/var/www
        - ./nginx/conf/:/etc/nginx/conf.d/:ro
        - ./certbot/www:/var/www/certbot/:ro
        - ./certbot/conf/:/etc/nginx/ssl/:ro


    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw
